name: ssmup-back
services:
  postgres:
    image: postgres:15-alpine
    container_name: ssmup_db
    environment:
      POSTGRES_DB: ssmup
      POSTGRES_USER: ssmup
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ssmup_api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ssmup
      SPRING_DATASOURCE_USERNAME: ssmup
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'

volumes:
  postgres_data: